# UltimateSensor Ethernet Basic Configuration
# This configuration excludes the Particulate Matter (PM) sensor.
# Use this file if your device does not include the PM/fine dust sensor and uses Ethernet.

substitutions:
  device_name: ultimatesensor
  friendly_name: "UltimateSensor"
  ultimatesensor_software_version: "1.10"
  ultimatesensor_hardware_version: "V1-Basic"
  ultimatesensor_connection_type: "Ethernet"

packages:
  base: !include base.yaml
  ld2450_zones: !include zones.yaml
  net: !include ethernet.yaml

dashboard_import:
  package_import_url: github://smarthomeshop/ultimatesensor/ultimatesensor-v1/ultimatesensor-ethernet-basic.yaml@main
