# UltimateSensor Ethernet Basic Cloud Configuration

substitutions:
  device_name: ultimatesensor
  friendly_name: "UltimateSensor"
  ultimatesensor_software_version: "1.10"
  ultimatesensor_hardware_version: "V1-Basic"
  ultimatesensor_connection_type: "Ethernet"
  cloud_mac_sensor_id: ethernet_mac
  cloud_ip_sensor_id: ethernet_ip

packages:
  base: !include base.yaml
  ld2450_zones: !include zones.yaml
  net: !include ethernet.yaml
  cloud_net: !include cloud-ethernet.yaml
  cloud: !include cloud.yaml
  zones: !include cloud-zones.yaml

dashboard_import:
  package_import_url: github://smarthomeshop/ultimatesensor/ultimatesensor-v1/ultimatesensor-ethernet-basic-cloud.yaml@main
